spring.application.name=backend-service-mongp
server.port=8001
#spring.datasource.url=jdbc:mariadb://localhost:3306/db_mongp
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#
spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.datasource.url=${DB_URL:jdbc:postgresql://db-postgres:5432/db_mongp}
spring.datasource.username=admin
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
